[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tokio-util = { version = "0", features = ["codec"] }
futures = "0"
