[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
tokio.workspace = true
tokio-util.workspace = true

shared.workspace = true
